# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('BBC', 'BBC'), ('CNN', 'CNN')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source'], name='news_article_source_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='news_article_published_at_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['url'], name='news_article_url_idx'),
        ),
    ]
