# Generated by Django 4.2.7 on 2025-09-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='news_articl_source_594688_idx',
            old_name='news_article_source_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='news_articl_publish_90ca8c_idx',
            old_name='news_article_published_at_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='news_articl_url_957495_idx',
            old_name='news_article_url_idx',
        ),
    ]
